server:
  port: 8080
#  servlet:
#    context-path: /admin   # 如果配置后打开的地址为 http://localhost:8080/admin/，不配置地址为 http://localhost:8080/

spring:
  thymeleaf:
    prefix: classpath:/html/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html

  datasource:
    url: jdbc:mysql://localhost:3306/newhope?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: store
  mvc:
    static-path-pattern: /static/**

logging:
  config: classpath:logback.xml

